language: php

sudo: false

php:
- 7.3

matrix:
  fast_finish: true

cache:
  directories:
  - $HOME/.composer/cache

install:
- composer install --prefer-dist --no-interaction

script:
- vendor/bin/phpunit